apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-docker
  name: hello-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-docker
    spec:
      containers:
      - image: sambitc/hello-docker-az:azure
        name: hello-docker-az
        resources: {}
status: {}
